### ISSUE TITLE
Conflicting pyarrow version warning

### ISSUE THREAD

**Issue by sfc-gh-asaini** [Snowflake-Labs/snowcli#31]
### Steps to repro
1. Install snowcli
```sh
$ pip install snowflake-cli-labs
```

2. Install streamlit
```sh
$ pip install streamlit
```

3. Run any snow command
```sh
$ snow --help
```

This results in the following warning showing in shell

```sh
❯ snow --help
/Users/asaini/.local/share/virtualenvs/test-11-2-uHfu31ul/lib/python3.10/site-packages/snowflake/connector/options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (10.0.0), please install a version that adheres to: 'pyarrow<8.1.0,>=8.0.0; extra == "pandas"'
  warn_incompatible_dep(

 Usage: snow [OPTIONS] COMMAND [ARGS]...

 SnowCLI - A CLI for Snowflake
...
...
```

**Comment by sfc-gh-jhollan** [comment]
This is due to the underyling Snowflake Python connector this CLI uses. The versions of PyArrow aren't always updated as frequently so does require running in an environment, or virtual environment, that has the right version.

Probably a better way to get around this, but for sake of this documenting one workaround is to [install via source](https://github.com/Snowflake-Labs/snowcli#install-from-source) using the virtual environment approach. Then whenever you want to use the `snow` CLI, activating the virtual environment and it should use that version of pyarrow.

Longer term there is a work item to streamline this dependency / remove surfacing in Python connector, timeline TBD

**Comment by sfc-gh-anugupta** [comment]
Yes the python connector is planned to be updated for this.
